# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="5ec64de8-c642-4765-85d0-6accab1e423d"

# Отправлять уведомление на почту vlad1slaw19982@gmail.com, если сборка упала
notifications:
  email:
    recipients:
      -vlad1slaw19982@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
